version: '3'

services:
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql
    networks:
      - Inception
    restart: always

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    ports:
      - 9000:9000
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_started
    volumes:
      - frontVolumes:/var/www/wordpress
    networks:
      - Inception
    restart: always

  nginx:
    image: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    depends_on:
      wordpress:
        condition: service_started
    volumes:
      - frontVolumes:/var/www/html
    networks:
      - Inception
    restart: always

networks:
  Inception:
    driver: bridge

volumes:
  frontVolumes:
    name: "wp-ng-files"
  database:
    name: "mariadb-database"