version: '3'

networks:
  Inception:
    name: Inception
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/araqioui/data/wordpress'
  database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/araqioui/data/mariadb'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql
    networks:
      - Inception
    restart: on-failure

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - Inception
    restart: on-failure

  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - Inception
    restart: on-failure
